export const constants = {
    GETOFFICES_REQUEST: 'GET_OFFICES_REQUEST',
    GETOFFICES_SUCCESS: 'GET_OFFICES_SUCCESS',
    GETOFFICES_FAILURE: 'GET_OFFICES_FAILURE',

    GETPROJECTS_REQUEST: 'GET_PROJECTS_REQUEST',
    GETPROJECTS_SUCCESS: 'GET_PROJECTS_SUCCESS',
    GETPROJECTS_FAILURE: 'GET_PROJECTS_FAILURE',

    GETMEMBERS_REQUEST: 'GET_MEMBERS_REQUEST',
    GETMEMBERS_SUCCESS: 'GET_MEMBERS_SUCCESS',
    GETMEMBERS_FAILURE: 'GET_MEMBERS_FAILURE',
};